server:
  port: 8083
spring:
  application:
    name: video-storage
  data:
    mongodb:
      uri: mongodb://mongodb:27017/smartvideo
      auto-index-creation: true
    redis:
      host: redis
      port: 6379
  cache:
    type: redis
    redis:
      time-to-live: 300000
      cache-null-values: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/smartvision

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_DEFAULTZONE:http://localhost:8761/eureka/}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    refresh:
      enabled: true
    loggers:
      enabled: true
  tracing:
    sampling:
      probability: 1.0
logging:
  level:
    org.springframework.data.mongodb: DEBUG
    com.mongodb: WARN
