server:
  port: 8085
spring:
  application:
    name: video-core
  data:
    redis:
      host: redis
      port: 6379
  cache:
    type: redis
    redis:
      time-to-live: 60000
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/smartvision

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_DEFAULTZONE:http://localhost:8761/eureka/}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
	refresh:
      enabled: true
    loggers:
      enabled: true
  tracing:
    sampling:
      probability: 1.0
resilience4j:
  circuitbreaker:
    instances:
      storageService:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5

logging:
  level:
    org.springframework.data.mongodb: DEBUG
    com.mongodb: WARN
